// Code generated by "stringer -type=LearningRate,Momentum types.go"; DO NOT EDIT.

package ann

import "fmt"

const _LearningRate_name = "ConstantInvScalingAdaptive"

var _LearningRate_index = [...]uint8{0, 8, 18, 26}

func (i LearningRate) String() string {
	i -= 101
	if i < 0 || i >= LearningRate(len(_LearningRate_index)-1) {
		return fmt.Sprintf("LearningRate(%d)", i+101)
	}
	return _LearningRate_name[_LearningRate_index[i]:_LearningRate_index[i+1]]
}

const (
	_Momentum_name_0 = "None"
	_Momentum_name_1 = "BasicMomentumNesterov"
)

var (
	_Momentum_index_0 = [...]uint8{0, 4}
	_Momentum_index_1 = [...]uint8{0, 13, 21}
)

func (i Momentum) String() string {
	switch {
	case i == 0:
		return _Momentum_name_0
	case 302 <= i && i <= 303:
		i -= 302
		return _Momentum_name_1[_Momentum_index_1[i]:_Momentum_index_1[i+1]]
	default:
		return fmt.Sprintf("Momentum(%d)", i)
	}
}
